-- 请以 MySQL root（或具备 CREATE USER 权限的账号）执行。
CREATE DATABASE IF NOT EXISTS zhiyi
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'zhiyi_app'@'localhost' IDENTIFIED BY '请替换为本机强密码';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
  ON zhiyi.* TO 'zhiyi_app'@'localhost';
FLUSH PRIVILEGES;
