export class AppRoutes {
  static readonly SPLASH: string = 'pages/SplashPage';
  static readonly HOME: string = 'pages/MainTabPage';
  static readonly LOGIN: string = 'pages/LoginPage';
  static readonly REGISTER: string = 'pages/RegisterPage';
  static readonly ADD_MEMORY: string = 'pages/AddMemoryPage';
  static readonly MEMORY_LIST: string = 'pages/MemoryListPage';
  static readonly MEMORY_DETAIL: string = 'pages/MemoryDetailPage';
  static readonly MEMORY_TREE: string = 'pages/MemoryTreePage';
  static readonly COMMON_DAY: string = 'pages/CommonDayPage';
  static readonly SHARED_TREE: string = 'pages/SharedTreePage';
  static readonly MINE: string = 'pages/MinePage';
  static readonly TOOLBOX: string = 'pages/ToolboxPage';
  static readonly RECALL_CARD_LIST: string = 'pages/RecallCardListPage';
  static readonly RECALL_CARD_DETAIL: string = 'pages/RecallCardDetailPage';
  static readonly IMAGE_EDIT: string = 'pages/ImageEditPage';
  static readonly CROP: string = 'pages/CropPage';
  static readonly ENHANCE: string = 'pages/EnhancePage';
  static readonly IMAGE_VIEW: string = 'pages/ImageViewPage';
}
