export class AppRoutes {
  static readonly HOME: string = 'pages/MainTabPage';
  static readonly LOGIN: string = 'pages/LoginPage';
  static readonly REGISTER: string = 'pages/RegisterPage';
  static readonly ADD_MEMORY: string = 'pages/AddMemoryPage';
  static readonly MEMORY_LIST: string = 'pages/MemoryListPage';
  static readonly MEMORY_DETAIL: string = 'pages/MemoryDetailPage';
  static readonly MEMORY_TREE: string = 'pages/MemoryTreePage';
  static readonly COMMON_DAY: string = 'pages/CommonDayPage';
  static readonly SHARED_TREE: string = 'pages/SharedTreePage';
  static readonly MINE: string = 'pages/MinePage';
  static readonly TOOLBOX: string = 'pages/ToolboxPage';
}
